name: '*next*'
package:
  - '@skyra/env-utilities'
  - '@skyra/http-framework'
  - '@skyra/http-framework-i18n'
  - '@skyra/i18next-backend'
  - '@skyra/logger'
  - '@skyra/shared-http-pieces'
  # TODO: Fix name when package.json is created
  # - '@skyra/shared-gateway-pieces'
  - '@skyra/start-banner'
