name: '*next*'
package:
  - '@skyra/env-utilities'
  - '@skyra/http-framework'
  - '@skyra/http-framework-i18n'
  - '@skyra/i18next-backend'
  - '@skyra/influx-utilities'
  - '@skyra/logger'
  - '@skyra/reddit-helpers'
  - '@skyra/safe-fetch'
  - '@skyra/shared-http-pieces'
  - '@skyra/shared-influx-pieces'
  - '@skyra/start-banner'
  - '@skyra/twitch-helpers'
  - '@skyra/weather-helpers'
