name: shared-http-pieces
org: skyra
install: true
packagePath: packages/shared-http-pieces
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: skyra-project/archid-components
gitHostVariant: github
