name: logger
org: skyra
install: true
packagePath: packages/logger
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: skyra-project/archid-components
gitHostVariant: github
