name: i18next-backend
org: skyra
install: true
packagePath: packages/i18next-backend
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: skyra-project/archid-components
gitHostVariant: github
