name: http-framework
org: skyra
install: true
packagePath: packages/http-framework
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: skyra-project/archid-components
gitHostVariant: github
