name: influx-utilities
org: skyra
install: true
packagePath: packages/influx-utilities
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: skyra-project/archid-components
gitHostVariant: github
