name: safe-fetch
org: skyra
install: true
packagePath: packages/safe-fetch
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: skyra-project/archid-components
gitHostVariant: github
