name: shared-influx-pieces
org: skyra
install: true
packagePath: packages/shared-influx-pieces
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: skyra-project/archid-components
gitHostVariant: github
