name: reddit-helpers
org: skyra
install: true
packagePath: packages/reddit-helpers
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: skyra-project/archid-components
gitHostVariant: github
