name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Next to npm
    runs-on: ubuntu-latest
    if: github.repository_owner == 'skyra-project'
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - env-utilities
          - http-framework
          - http-framework-i18n
          - i18next-backend
          - influx-utilities
          - logger
          - reddit-helpers
          - safe-fetch
          - shared-http-pieces
          - shared-influx-pieces
          - start-banner
          - twitch-helpers
          - weather-helpers
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build all packages
        run: yarn build
      - name: Bump Versions & Publish
        working-directory: packages/${{ matrix.package }}
        run: |
          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://registry.yarnpkg.com"

          yarn bump --preid "next.$(git rev-parse --verify --short HEAD)" --skip-changelog

          yarn npm publish --tag next --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
